# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

plugins:
  - jekyll-redirect-from

title: "PyCon UK 2025"

# Flags for when thingsâ„¢ happen
cfp_open: true
cfp_closed: true
fin_aid_open: false
fin_aid_closed: true
spons_prosp_avail: true
tickets_open: true
schedule_ready: true
schedule_final: false
show_sponsors: true
show_django_girls: true
django_girls_applications_open: true

# When changing the year, please change it in the title, above. We can't use vars in vars.
con_year: 2025
con_startDate: "2025-09-19"
con_start: Friday 19th September
con_endDate: "2025-09-22"
con_finish: Monday 22nd September
con_financial_assistance_deadline: "17:00 (Europe/London) on Friday, 11th July"
cfp_end: Sunday 11th May 2025
django_girls_date: Saturday 20th September
young_coders_date: Saturday 20th September

con_location: Contact Theatre, Manchester
con_director: Becky Smith

con_vat_number: GB431251341
# Don't forget to update the invoicing page if the con_company changes
con_company: UKPA Trading Ltd. (a company registered in England and Wales <a href="https://beta.companieshouse.gov.uk/company/12254310">no.&nbsp;12254310</a>)
ukpa: The UK&nbsp;Python Association (a charity registered in England and Wales <a href="https://register-of-charities.charitycommission.gov.uk/en/charity-search/-/charity-details/5101629?_uk_gov_ccew_onereg_charitydetails_web_portlet_CharityDetailsPortlet_organisationNumber=5101629">no.&nbsp;1173471</a>)

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2025.pyconuk.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
source: src
destination: _site
markdown: kramdown

sass:
  style: "compact"

permalink: "/:year/:month/:title/"
